/** Static ranking attributes from Frankmo89/us-parks-recommender parks.csv (frozen). */
import type { BudgetTier, CrowdLevel, DaysNeeded, Difficulty, RankingPark } from "./ranking";

export type RankingCatalogEntry = Omit<RankingPark, "name">;

export const RANKING_CATALOG: Record<string, RankingCatalogEntry> = {
  acad: {
    park_code: "acad",
    lat: 44.35,
    lon: -68.21,
    biome: "coast",
    tags: "hiking|scenic_drive|family|coast|wildlife|camping",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "5,6,7,8,9,10",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  npsa: {
    park_code: "npsa",
    lat: -14.26,
    lon: -170.68,
    biome: "rainforest",
    tags: "hiking|coast|wildlife|family",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "5,6,7,8,9",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  arch: {
    park_code: "arch",
    lat: 38.68,
    lon: -109.57,
    biome: "desert",
    tags: "hiking|scenic_drive|family|desert|stargazing|photography",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "3,4,5,9,10,11",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  badl: {
    park_code: "badl",
    lat: 43.75,
    lon: -102.5,
    biome: "prairie",
    tags: "hiking|scenic_drive|wildlife|family|stargazing|paleontology",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "5,6,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  bibe: {
    park_code: "bibe",
    lat: 29.25,
    lon: -103.25,
    biome: "desert",
    tags: "hiking|backpacking|stargazing|desert|wildlife|scenic_drive|camping",
    difficulty: "moderate" as Difficulty,
    days_needed: "4-7" as DaysNeeded,
    best_months: "2,3,4,10,11",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 1,
  },
  bisc: {
    park_code: "bisc",
    lat: 25.65,
    lon: -80.08,
    biome: "coast",
    tags: "water|wildlife|family|coast|boat",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "12,1,2,3,4",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  blca: {
    park_code: "blca",
    lat: 38.57,
    lon: -107.72,
    biome: "canyon",
    tags: "hiking|scenic_drive|photography|canyon|stargazing",
    difficulty: "moderate" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "5,6,9,10",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  brca: {
    park_code: "brca",
    lat: 37.59,
    lon: -112.19,
    biome: "canyon",
    tags: "hiking|family|scenic_drive|photography|stargazing|canyon",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "5,6,9,10",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  cany: {
    park_code: "cany",
    lat: 38.2,
    lon: -109.93,
    biome: "canyon",
    tags: "hiking|backpacking|scenic_drive|desert|stargazing|4x4",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "3,4,5,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  care: {
    park_code: "care",
    lat: 38.2,
    lon: -111.17,
    biome: "canyon",
    tags: "hiking|scenic_drive|family|desert|stargazing",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "4,5,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  cave: {
    park_code: "cave",
    lat: 32.17,
    lon: -104.44,
    biome: "cave",
    tags: "family|cave|wildlife|easy_walk",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "3,4,5,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  chis: {
    park_code: "chis",
    lat: 34.01,
    lon: -119.42,
    biome: "island",
    tags: "hiking|wildlife|water|boat|backpacking|kayak",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "4,5,6,9,10",
    crowd: "low" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 1,
  },
  cong: {
    park_code: "cong",
    lat: 33.78,
    lon: -80.78,
    biome: "wetland",
    tags: "hiking|family|wildlife|water|boardwalk",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "3,4,10,11",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  crla: {
    park_code: "crla",
    lat: 42.94,
    lon: -122.1,
    biome: "alpine",
    tags: "hiking|scenic_drive|family|photography|winter",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "7,8,9",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  cuva: {
    park_code: "cuva",
    lat: 41.24,
    lon: -81.55,
    biome: "forest",
    tags: "hiking|family|scenic_drive|easy_walk|biking",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "5,6,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  deva: {
    park_code: "deva",
    lat: 36.24,
    lon: -116.82,
    biome: "desert",
    tags: "hiking|scenic_drive|stargazing|desert|photography|family",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "11,12,1,2,3",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  dena: {
    park_code: "dena",
    lat: 63.33,
    lon: -150.5,
    biome: "tundra",
    tags: "wildlife|scenic_drive|hiking|backpacking|photography",
    difficulty: "challenging" as Difficulty,
    days_needed: "4-7" as DaysNeeded,
    best_months: "6,7,8",
    crowd: "medium" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  drto: {
    park_code: "drto",
    lat: 24.63,
    lon: -82.87,
    biome: "island",
    tags: "water|wildlife|boat|history|snorkeling",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "12,1,2,3,4",
    crowd: "low" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  ever: {
    park_code: "ever",
    lat: 25.32,
    lon: -80.93,
    biome: "wetland",
    tags: "wildlife|water|hiking|family|boat|birding",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "12,1,2,3",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  gaar: {
    park_code: "gaar",
    lat: 67.78,
    lon: -153.3,
    biome: "tundra",
    tags: "backpacking|wildlife|wilderness|remote",
    difficulty: "challenging" as Difficulty,
    days_needed: "7+" as DaysNeeded,
    best_months: "6,7,8",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  jeff: {
    park_code: "jeff",
    lat: 38.63,
    lon: -90.19,
    biome: "urban",
    tags: "family|history|easy_walk|urban",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "4,5,9,10",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  glac: {
    park_code: "glac",
    lat: 48.76,
    lon: -113.79,
    biome: "alpine",
    tags: "hiking|scenic_drive|wildlife|backpacking|photography|alpine",
    difficulty: "moderate" as Difficulty,
    days_needed: "4-7" as DaysNeeded,
    best_months: "7,8,9",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  glba: {
    park_code: "glba",
    lat: 58.5,
    lon: -137.0,
    biome: "coast",
    tags: "wildlife|boat|water|photography|remote",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "6,7,8",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  grca: {
    park_code: "grca",
    lat: 36.06,
    lon: -112.14,
    biome: "canyon",
    tags: "hiking|scenic_drive|family|photography|backpacking|canyon",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "4,5,9,10",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  grte: {
    park_code: "grte",
    lat: 43.73,
    lon: -110.8,
    biome: "alpine",
    tags: "hiking|wildlife|scenic_drive|backpacking|photography|alpine",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "6,7,8,9",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  grba: {
    park_code: "grba",
    lat: 38.98,
    lon: -114.3,
    biome: "alpine",
    tags: "hiking|stargazing|cave|scenic_drive|low_crowd",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "6,7,8,9",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 1,
  },
  grsa: {
    park_code: "grsa",
    lat: 37.73,
    lon: -105.51,
    biome: "desert",
    tags: "hiking|family|stargazing|sand|photography",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "5,6,9",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  grsm: {
    park_code: "grsm",
    lat: 35.68,
    lon: -83.53,
    biome: "forest",
    tags: "hiking|scenic_drive|family|wildlife|waterfalls|camping",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "4,5,6,9,10",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  gumo: {
    park_code: "gumo",
    lat: 31.92,
    lon: -104.87,
    biome: "desert",
    tags: "hiking|backpacking|desert|low_crowd",
    difficulty: "challenging" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "3,4,10,11",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 1,
  },
  hale: {
    park_code: "hale",
    lat: 20.72,
    lon: -156.17,
    biome: "volcano",
    tags: "hiking|sunrise|scenic_drive|volcano|stargazing",
    difficulty: "moderate" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "1,2,3,4,5,6,7,8,9,10,11,12",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  havo: {
    park_code: "havo",
    lat: 19.38,
    lon: -155.2,
    biome: "volcano",
    tags: "hiking|family|volcano|scenic_drive|photography",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "1,2,3,4,5,6,7,8,9,10,11,12",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  hosp: {
    park_code: "hosp",
    lat: 34.51,
    lon: -93.05,
    biome: "forest",
    tags: "family|easy_walk|history|hot_springs",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "3,4,5,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  indu: {
    park_code: "indu",
    lat: 41.65,
    lon: -87.07,
    biome: "coast",
    tags: "hiking|family|coast|easy_walk|birding",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "5,6,9",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  isro: {
    park_code: "isro",
    lat: 48.1,
    lon: -88.55,
    biome: "island",
    tags: "backpacking|hiking|wildlife|water|boat|wilderness",
    difficulty: "challenging" as Difficulty,
    days_needed: "4-7" as DaysNeeded,
    best_months: "6,7,8,9",
    crowd: "low" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 1,
  },
  jotr: {
    park_code: "jotr",
    lat: 33.79,
    lon: -115.9,
    biome: "desert",
    tags: "hiking|climbing|stargazing|desert|camping|family|photography",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "10,11,12,1,2,3,4",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  katm: {
    park_code: "katm",
    lat: 58.5,
    lon: -155.0,
    biome: "tundra",
    tags: "wildlife|bears|boat|photography|remote",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "7,8",
    crowd: "low" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  kefj: {
    park_code: "kefj",
    lat: 59.92,
    lon: -149.65,
    biome: "coast",
    tags: "wildlife|boat|hiking|water|photography",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "6,7,8",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  kica: {
    park_code: "kica",
    lat: 36.8,
    lon: -118.55,
    biome: "forest",
    tags: "hiking|scenic_drive|backpacking|waterfalls|alpine|family",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "6,7,8,9",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  kova: {
    park_code: "kova",
    lat: 67.55,
    lon: -159.28,
    biome: "tundra",
    tags: "wilderness|remote|wildlife|backpacking",
    difficulty: "challenging" as Difficulty,
    days_needed: "7+" as DaysNeeded,
    best_months: "6,7,8",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  lacl: {
    park_code: "lacl",
    lat: 60.97,
    lon: -153.42,
    biome: "tundra",
    tags: "wildlife|wilderness|water|remote|backpacking",
    difficulty: "challenging" as Difficulty,
    days_needed: "4-7" as DaysNeeded,
    best_months: "6,7,8",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  lavo: {
    park_code: "lavo",
    lat: 40.49,
    lon: -121.51,
    biome: "volcano",
    tags: "hiking|family|volcano|scenic_drive|camping",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "7,8,9",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  maca: {
    park_code: "maca",
    lat: 37.18,
    lon: -86.1,
    biome: "cave",
    tags: "family|cave|hiking|easy_walk|history",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "4,5,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  meve: {
    park_code: "meve",
    lat: 37.18,
    lon: -108.49,
    biome: "canyon",
    tags: "family|history|scenic_drive|archaeology|hiking",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "5,6,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  mora: {
    park_code: "mora",
    lat: 46.85,
    lon: -121.75,
    biome: "alpine",
    tags: "hiking|scenic_drive|family|wildflowers|alpine|photography",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "7,8,9",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  neri: {
    park_code: "neri",
    lat: 38.07,
    lon: -81.08,
    biome: "forest",
    tags: "hiking|climbing|water|scenic_drive|family",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "5,6,9,10",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  noca: {
    park_code: "noca",
    lat: 48.7,
    lon: -121.2,
    biome: "alpine",
    tags: "hiking|backpacking|alpine|low_crowd|photography|wildlife",
    difficulty: "challenging" as Difficulty,
    days_needed: "4-7" as DaysNeeded,
    best_months: "7,8,9",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 1,
  },
  olym: {
    park_code: "olym",
    lat: 47.8,
    lon: -123.7,
    biome: "rainforest",
    tags: "hiking|coast|rainforest|hot_springs|backpacking|family",
    difficulty: "moderate" as Difficulty,
    days_needed: "4-7" as DaysNeeded,
    best_months: "6,7,8,9",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  pefo: {
    park_code: "pefo",
    lat: 35.07,
    lon: -109.78,
    biome: "desert",
    tags: "hiking|scenic_drive|family|desert|paleontology",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "3,4,5,10,11",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  pinn: {
    park_code: "pinn",
    lat: 36.48,
    lon: -121.16,
    biome: "chaparral",
    tags: "hiking|climbing|wildlife|family|cave",
    difficulty: "moderate" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "2,3,4,10,11",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  redw: {
    park_code: "redw",
    lat: 41.3,
    lon: -124.0,
    biome: "rainforest",
    tags: "hiking|family|scenic_drive|coast|wildlife",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "5,6,7,8,9",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  romo: {
    park_code: "romo",
    lat: 40.4,
    lon: -105.58,
    biome: "alpine",
    tags: "hiking|scenic_drive|wildlife|family|alpine|photography",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "6,7,8,9",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  sagu: {
    park_code: "sagu",
    lat: 32.25,
    lon: -110.5,
    biome: "desert",
    tags: "hiking|family|desert|stargazing|easy_walk",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "11,12,1,2,3,4",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  seki: {
    park_code: "seki",
    lat: 36.49,
    lon: -118.56,
    biome: "forest",
    tags: "hiking|family|scenic_drive|giant_trees|alpine",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "6,7,8,9",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  shen: {
    park_code: "shen",
    lat: 38.53,
    lon: -78.35,
    biome: "forest",
    tags: "hiking|scenic_drive|family|waterfalls|camping",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "4,5,6,9,10",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  thro: {
    park_code: "thro",
    lat: 46.97,
    lon: -103.45,
    biome: "prairie",
    tags: "hiking|wildlife|scenic_drive|family|low_crowd",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "5,6,9",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  viis: {
    park_code: "viis",
    lat: 18.33,
    lon: -64.73,
    biome: "coast",
    tags: "water|hiking|family|snorkeling|coast|beach",
    difficulty: "easy" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "12,1,2,3,4",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  voya: {
    park_code: "voya",
    lat: 48.5,
    lon: -92.88,
    biome: "forest",
    tags: "water|boat|wildlife|camping|fishing",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "6,7,8,9",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 1,
  },
  whsa: {
    park_code: "whsa",
    lat: 32.78,
    lon: -106.17,
    biome: "desert",
    tags: "hiking|family|sand|photography|stargazing",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "3,4,10,11",
    crowd: "medium" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  wica: {
    park_code: "wica",
    lat: 43.57,
    lon: -103.48,
    biome: "prairie",
    tags: "cave|wildlife|hiking|family",
    difficulty: "easy" as Difficulty,
    days_needed: "1" as DaysNeeded,
    best_months: "5,6,9,10",
    crowd: "low" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "low" as BudgetTier,
    remote: 0,
  },
  wrst: {
    park_code: "wrst",
    lat: 61.0,
    lon: -142.0,
    biome: "alpine",
    tags: "wilderness|backpacking|remote|glacier|wildlife",
    difficulty: "challenging" as Difficulty,
    days_needed: "7+" as DaysNeeded,
    best_months: "6,7,8",
    crowd: "low" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "high" as BudgetTier,
    remote: 1,
  },
  yell: {
    park_code: "yell",
    lat: 44.6,
    lon: -110.5,
    biome: "alpine",
    tags: "wildlife|scenic_drive|family|hiking|geothermal|camping",
    difficulty: "easy" as Difficulty,
    days_needed: "4-7" as DaysNeeded,
    best_months: "5,6,7,8,9",
    crowd: "high" as CrowdLevel,
    permit_likely: 0,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  yose: {
    park_code: "yose",
    lat: 37.75,
    lon: -119.6,
    biome: "alpine",
    tags: "hiking|scenic_drive|family|waterfalls|backpacking|climbing|photography",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "5,6,7,8,9,10",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
  zion: {
    park_code: "zion",
    lat: 37.3,
    lon: -113.05,
    biome: "canyon",
    tags: "hiking|canyon|family|photography|scenic_drive|permits",
    difficulty: "moderate" as Difficulty,
    days_needed: "2-3" as DaysNeeded,
    best_months: "3,4,5,10,11",
    crowd: "high" as CrowdLevel,
    permit_likely: 1,
    budget_tier: "mid" as BudgetTier,
    remote: 0,
  },
};
