// Builds public/data/zcta-centroids-<year>.txt from the US Census Bureau ZCTA
// gazetteer — the ZIP → lat/lon table the quiz uses to compute drive times.
//
// Nothing in the generated file is typed by hand: this script downloads the
// pinned gazetteer year, keeps the internal point (INTPTLAT/INTPTLONG) of every
// ZCTA rounded to 1 decimal (~11 km — far below the 3/6/10 h drive buckets), and
// writes one "<zip> <lat>,<lon>" per line. Same convention as
// scripts/build-soul.ts and scripts/sync-engine.ts.
//
// A plain text file on purpose, not a .ts module: as a 530 KB string literal it
// made `vite build` take 6+ minutes (see src/lib/zip-centroids.ts).
//
// The year and output path come from src/lib/zip-centroids.ts so the script and
// the app can never disagree on the file name.
//
//   npm run build:zip-centroids
//
// Source: https://www.census.gov/geographies/reference-files/time-series/geo/gazetteer-files.html
// Census Bureau gazetteer files are US Government works — public domain.
// Requires network (public HTTPS, no auth). No new dependencies: the .zip is
// read with node:zlib.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { inflateRawSync } from "node:zlib";
import { ZCTA_GAZETTEER_YEAR as GAZETTEER_YEAR, ZCTA_TABLE_PATH } from "../src/lib/zip-centroids";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_URL =
  `https://www2.census.gov/geo/docs/maps-data/data/gazetteer/${GAZETTEER_YEAR}_Gazetteer/${GAZETTEER_YEAR}_Gaz_zcta_national.zip`;
const TARGET = `public${ZCTA_TABLE_PATH}`;

/** Extracts the single file in a .zip archive (stored or deflated). */
function unzipSingleFile(zip: Buffer): Buffer {
  // End of central directory record: last occurrence of its signature.
  const eocd = zip.lastIndexOf(Buffer.from([0x50, 0x4b, 0x05, 0x06]));
  if (eocd < 0) throw new Error("not a zip archive (no end-of-central-directory record)");
  const centralDirOffset = zip.readUInt32LE(eocd + 16);
  if (zip.readUInt32LE(centralDirOffset) !== 0x02014b50) throw new Error("bad central directory header");
  const method = zip.readUInt16LE(centralDirOffset + 10);
  const compressedSize = zip.readUInt32LE(centralDirOffset + 20);
  const localHeaderOffset = zip.readUInt32LE(centralDirOffset + 42);
  if (zip.readUInt32LE(localHeaderOffset) !== 0x04034b50) throw new Error("bad local file header");
  const nameLength = zip.readUInt16LE(localHeaderOffset + 26);
  const extraLength = zip.readUInt16LE(localHeaderOffset + 28);
  const start = localHeaderOffset + 30 + nameLength + extraLength;
  const data = zip.subarray(start, start + compressedSize);
  if (method === 0) return data;
  if (method === 8) return inflateRawSync(data);
  throw new Error(`unsupported zip compression method ${method}`);
}

function round1(n: number): string {
  const r = Math.round(n * 10) / 10;
  return (Object.is(r, -0) ? 0 : r).toString();
}

async function main() {
  const res = await fetch(SOURCE_URL);
  if (!res.ok) throw new Error(`GET ${SOURCE_URL} → ${res.status}`);
  const text = unzipSingleFile(Buffer.from(await res.arrayBuffer())).toString("utf8");

  const lines = text.split(/\r?\n/).filter((l) => l.trim() !== "");
  const header = lines[0].split("|").map((h) => h.trim());
  const iZip = header.indexOf("GEOID");
  const iLat = header.indexOf("INTPTLAT");
  const iLon = header.indexOf("INTPTLONG");
  if (iZip < 0 || iLat < 0 || iLon < 0) throw new Error(`unexpected gazetteer header: ${lines[0]}`);

  const entries: string[] = [];
  for (const line of lines.slice(1)) {
    const cols = line.split("|").map((c) => c.trim());
    const zip = cols[iZip];
    const lat = Number(cols[iLat]);
    const lon = Number(cols[iLon]);
    if (!/^\d{5}$/.test(zip) || !Number.isFinite(lat) || !Number.isFinite(lon)) {
      throw new Error(`bad gazetteer row: ${line}`);
    }
    entries.push(`${zip} ${round1(lat)},${round1(lon)}`);
  }
  entries.sort();

  const out = [
    `# AUTO-GENERATED by scripts/build-zip-centroids.ts — DO NOT EDIT BY HAND.`,
    `# Source: US Census Bureau ${GAZETTEER_YEAR} ZCTA gazetteer (public domain), ${SOURCE_URL}`,
    `# ${entries.length} ZCTAs. One "<5-digit ZCTA> <lat>,<lon>" per line — internal point, 1 decimal.`,
    `# Fetched on demand by src/lib/zip-centroids.ts; never bundled into JS.`,
    ...entries,
    ``,
  ].join("\n");

  mkdirSync(dirname(join(ROOT, TARGET)), { recursive: true });
  writeFileSync(join(ROOT, TARGET), out, "utf8");
  console.log(`[build-zip-centroids] Written: ${TARGET} (${entries.length} ZCTAs, ${out.length} bytes)`);
}

main().catch((err) => {
  console.error(`[build-zip-centroids] ERROR: ${err instanceof Error ? err.message : err}`);
  process.exit(1);
});
